### ISSUE TITLE
Issue with encryption

### ISSUE THREAD

**Issue by anthrophous** [xxtea/xxtea-delphi#1]
I'm trying to use your library in my software, but I cannot uderstand why the string I encrypt change always.
Here the string that I try to encrypt:
`'<xml><email>xxxx@gmail.com</email><password>passsssssword</password><paypalTransactionId>12345645457dfd</paypalTransactionId><uid>000306C3-02100800-7FFAFBFF-BFEBFBFF</uid><productType>commenter</productType><version>1.0.0</version></xml>'`

**Comment by andot** [comment]
I don't undestand what you mean.

**Comment by anthrophous** [comment]
Here my code in Delphi:
```
    S := BytesOf(UTF8String(postData));
    K := BytesOf(FormMainGlobalVariables.CRYPTKEY);
    EncryptedData := XXTEA.Encrypt(S, K);

    lParamList := TStringList.Create;
    lParamList.Add('data='+Base64.Encode(EncryptedData));
```
The variable postData is:
`<xml><email>xxxx@gmail.com</email><password>passsssssword</password><paypalTransactionId>12345645457dfd</paypalTransactionId><uid>000306C3-02100800-7FFAFBFF-BFEBFBFF</uid><productType>commenter</productType><version>1.0.0</version></xml>`
While CRYPTKEY is the key for encryption and it is a constant.
I don't understand because the variable EncryptedData change every time I apply your algorithm. If I crypt a string and the values passed to your  XXTEA.Encrypt are the same ones the encrypted string should to be always the same one.

**Comment by andot** [comment]
I still don't understand what you mean.

**Comment by anthrophous** [comment]
I am testing your example code.
the final instrction should give me the initial string but the instruction 'Base64.Encode(ED)'  return this string 'QncB1C0rHQoZ1eRiPM4dsZtRi9pNrp7sqvX76cFXvrrIHXL6'
How I can get the original string that in your example is in variable S?

**Comment by andot** [comment]
ED is the original encrypted binary string.
DD is the decrypted binary string.
But ED and DD is TBytes type.
The ED is the binary string, so you can't convert it to normal string.
But you can use `StringOf` function on DD, it will change the DD to the normal string.

**Comment by anthrophous** [comment]
if I change your example to this line:
Writeln(Stringof(ED));
It doesn't work.
Perhaps something is wrong. you can write code as example.

**Comment by andot** [comment]
**The ED is the binary string, so you can't convert it to normal string.**

**You only can use StringOf function on DD.**

**Comment by anthrophous** [comment]
OK, I solved. 
Here the solution: Writeln(Stringof(DD)).
I used your algorithm to communicate Delphi-PHP by HTML post so now my communication is crypted and your encryption library is the only one that works on Windows and MacOSX without no problem.
thx again for your library.
