### ISSUE TITLE
not sport lazarus.

### ISSUE THREAD

**Issue by weidongbcn** [xxtea/xxtea-delphi#2]
lazarus 下的加密结果跟delphi出来的不一样。
delphi下可以解密，lazarus下解密不出来。

**Comment by MHumm** [comment]
If you can write your issue in English you might get more answers I guess.

**Comment by weidongbcn** [comment]
I think It is FPC bug, becuase FPC  not nulling the RESULT array..
so I do changge:

function ToUint32Array(const Data: TBytes; IncludeLength: Boolean): TUint32Array;
var
  N, I, L: TUint32; 
  v: TUint32Array;
begin
  L := Length(Data);
  if ((L and 3) = 0) then N := L shr 2 else N := (L shr 2) + 1;
  if (IncludeLength) then begin
    SetLength(v, N + 1);
    v[N] := L;
  end
  else SetLength(v, N);

  for I := 0 to L - 1 do
  begin
    v[I shr 2] := v[I shr 2] or (uint32( Data) shl ((I and 3) shl 3));
  end;
    result:=v;
end;

**Comment by gcarreno** [comment]
Hey there,

I guess that with the merge of PR #4 this issue can finally be closed?

Cheers,
Gus

**Comment by andot** [comment]
@gcarreno Thank you!

**Comment by gcarreno** [comment]
You are more than welcome!!
